### PR TITLE
Update config.py - uncommented OID 25

### PR DESCRIPTION
**Pull request by stefanks**
Hopefully solves https://github.com/aws/amazon-redshift-python-driver/issues/214

### CODE REVIEW

**Comment by Brooke-white** [comment]
Hey @stefanks , thanks for raising this PR. Can you share some details around the testing performed for this change. Mainly, did you confirm it resolved #214 i.e. were you able to successfully issue the query which previously was not working? If so, could you please add an integration test which issues this query so we can have coverage for this change in our CI?

**Comment by stefanks** [comment]
@Brooke-white not tested yet, having trouble setting up the dev environment with all the tests and stuff. I'm on a mac with vscode.

**Comment by stefanks** [comment]
@Brooke-white can you help me with this?

**Comment by Brooke-white** [comment]
Hi @stefanks , my apologies for my delay in response on both this issue and the associated PR. I pulled in this PR and found it did not resolve the issue at hand. This is due to the limitations around Redshift's support for array based bind parameters as I mentioned in the issue. As such, my best recommendation at this time is the work around I provided in #214

**Pull request closed without merging**
